initial post setup
vtex-apps/curbside-pickup pull request #47
Opened 2022-11-11 16:45 UTC by shashidhar85

Curbside E2E Cypress Tests

2022-11-16 06:55 UTC, Syed-Vtex requested changes

2022-11-16 06:55 UTC, Syed-Vtex commented on cy-runner.yml
> +    board: ""
Update board

2022-11-16 06:55 UTC, Syed-Vtex commented on cy-runner.yml
> +      - vtex.curbside-pickup@0.x
we don't need to install curbside link is fine

2022-11-16 06:55 UTC, Syed-Vtex commented on cypress/support/gmail.js
> +    if (encodedMessage) {
This is the same code which we have in cy-runner right
Can you please use from there

2022-11-16 07:45 UTC, shashidhar85 commented on cypress/support/gmail.js
> +    if (encodedMessage) {
yes

2022-11-16 10:29 UTC, shashidhar85 commented on cypress/support/gmail.js
> +    if (encodedMessage) {
gmail file is not there in common folder, so I created new file in support.

2022-11-16 12:47 UTC, Syed-Vtex commented on package.json
>      "localeDirectory": "messages"
Drop package-lock.json

2022-11-16 12:47 UTC, Syed-Vtex commented on package.json
>      "localeDirectory": "messages"
@shashidhar85

2022-11-17 11:46 UTC, Syed-Vtex commented on cy-runner.yml
> +    enabled: true
@shashidhar85 
Update cypress to true in workflow files
Add qe-schedule.yml file

2022-11-17 11:47 UTC, shashidhar85 commented on cy-runner.yml
> +    enabled: true
yes

2022-11-17 12:08 UTC, Syed-Vtex commented on cypress/integration/2.3-rest-apis.spec.js
> +  mailNotification(processNotification, singleProductEnvs.orderIdEnv)
after we hit this api, are we receiving mail notification ?

2022-11-17 12:08 UTC, Syed-Vtex commented on cypress/integration/2.3-rest-apis.spec.js
> +  mailNotification(processNotification, singleProductEnvs.orderIdEnv)
@saravananvenkatesan

2022-11-17 12:08 UTC, shashidhar85 commented on cypress/integration/2.3-rest-apis.spec.js
> +  mailNotification(processNotification, singleProductEnvs.orderIdEnv)
@saravananvenkatesan please check this

2022-11-17 13:29 UTC, Syed-Vtex commented on package.json
> +  "dependencies": {
@thyarles suggested to move these packages to devDependencies
(Because, this is required only for cypress tests real app not uses it)

2022-11-17 14:02 UTC, Syed-Vtex approved these changes

2022-11-17 14:03 UTC, merged